### ISSUE TITLE
Missing User-Agent header prevents thumbnailing of images behind CloudFlare

### ISSUE THREAD

**Issue by gjost** [mariocesar/sorl-thumbnail#377]
TLDNR `sorl.thumbnail` cannot make thumbnails when they are behind a CDN service like CloudFlare. The problem seems to be a missing `User-Agent` header.

We have several Django sites in a colo.  One site makes thumbnails from images hosted on another site in the same cluster.  Everything worked fine until we started using CloudFlare.  Requests for thumbnails hang, time out, and no thumbnails would be generated.  Flipping CloudFlare development mode on and off makes no difference.  Everything works properly if thumbnails are requested from the source via its LAN IP.

This traceback comes from an email circa November 2014, when we first noticed the problem:

    >>> from sorl.thumbnail import get_thumbnail
    >>> get_thumbnail(u'http://ddr.densho.org/media/ddr-densho-35/ddr-densho-35-428-mezzanine-8a1585375c-a.jpg', '100x100')
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/sorl/thumbnail/shortcuts.py", line 8, in get_thumbnail
        return default.backend.get_thumbnail(file_, geometry_string, **options)
      File "/usr/local/lib/python2.7/dist-packages/sorl/thumbnail/base.py", line 56, in get_thumbnail
        source_image = default.engine.get_image(source)
      File "/usr/local/lib/python2.7/dist-packages/sorl/thumbnail/engines/convert_engine.py", line 53, in get_image
        fp.write(source.read())
      File "/usr/local/lib/python2.7/dist-packages/sorl/thumbnail/images.py", line 121, in read
        return self.storage.open(self.name).read()
      File "/usr/local/lib/python2.7/dist-packages/sorl/thumbnail/images.py", line 169, in open
        return urllib2.urlopen(name)
      File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 407, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 445, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    HTTPError: HTTP Error 403: Forbidden

As of version 12.2 `get_thumbnail` fails silently:

    >>> from sorl.thumbnail import get_thumbnail
    >>> t1 = get_thumbnail(
        'http://ddr.densho.org/media/ddr-densho-35/ddr-densho-35-428-mezzanine-8a1585375c-a.jpg',
        '100x100'
        )
    >>> t1.exists()
    False
    >>> t2 = get_thumbnail(
        'http://10.0.2.123/media/ddr-densho-35/ddr-densho-35-428-mezzanine-8a1585375c-a.jpg',
        '100x100'
        )
    >>> t2.exists()
    True

We worked around this by giving `sorl` image URLs with the internal IP rather than the domain name:

    {% load thumbnail %}
    {% thumbnail img_src_local "100x100" as thumb %}
    <a href="{{ OTHER_SITE_MEDIA_URL }}{{ img_src }}">
    <img src="{{ THIS_SITE_MEDIA_URL }}{{ thumb }}">
    </a>
    {% endthumbnail %}
    

The problem seems to be a missing `User-Agent` header:

    >>> import urllib2
    
    >>> # Local IP
    >>> urllib2.urlopen(
    ...     'http://10.0.2.123/media/ddr-densho-35/ddr-densho-35-428-mezzanine-8a1585375c-a.jpg'
    ...     )
    <addinfourl at 140556495617488 whose fp = <socket._fileobject object at 0x7fd5db8c6450>>
    
    >>> # Domain name
    >>> urllib2.urlopen(
    ...     'http://ddr.densho.org/media/ddr-densho-35/ddr-densho-35-428-mezzanine-8a1585375c-a.jpg'
    ...     )
    Traceback (most recent call last):
      File "<input>", line 2, in <module>
      File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 437, in open
        response = meth(req, response)
      File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python2.7/urllib2.py", line 475, in error
        return self._call_chain(*args)
      File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    HTTPError: HTTP Error 403: Forbidden
    
    >>> # Domain name with User-Agent
    >>> req = urllib2.Request(
    ...     'http://ddr.densho.org/media/ddr-densho-35/ddr-densho-35-428-mezzanine-8a1585375c-a.jpg',
    ...     headers={'User-Agent': "Django App"}
    ...     )
    >>> urllib2.urlopen(req)
    <addinfourl at 140556488154216 whose fp = <socket._fileobject object at 0x7fd5db8c6350>>

**Comment by mariocesar** [comment]
@gjost thanks for the detailed posts, I push a fix on the master branch, soon as I update the tests will release an official version with the fix
