### ISSUE TITLE
THUMBNAIL_DEBUG should not catch Exceptions

### ISSUE THREAD

**Issue by jplehmann** [mariocesar/sorl-thumbnail#420]
Is the intent of THUMBNAIL_DEBUG to not catch exceptions if True?

I have a class of errors caused by telling sorl to process non-image files (actually 404-like HTML files).  This produces logging like the following:
```
[ERROR] cannot identify image file <cStringIO.StringI object at 0x1120958b0>  [base:105]
Traceback (most recent call last):
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/sorl/thumbnail/base.py", line 103, in get_thumbnail
    source_image = default.engine.get_image(source)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/sorl/thumbnail/engines/pil_engine.py", line 49, in get_image
    return Image.open(buffer)
  File "/Users/john/.venv/mm/lib/python2.7/site-packages/PIL/Image.py", line 2288, in open
    % (filename if filename else fp))
IOError: cannot identify image file <cStringIO.StringI object at 0x1120958b0>
```
However it only logs the error even when I have the THUMBNAIL_DEBUG True.  Is that expected?  I would like to have to catch this exception myself.

**Comment by sunsetjunks** [comment]
Did you eventually find a way of catching sorl-thumbnail exceptions?
