### ISSUE TITLE
Getting thumbnail for specific JPEG generates "IOError: encoder error"

### ISSUE THREAD

**Issue by GeyseR** [mariocesar/sorl-thumbnail#441]
Hi!

When we try to get thumbnail for specific image, "IOError: encoder error -2 when writing image file" exception is raised.

Code for reproducing bug:
```python
obj = SomeModel.objects.get(id=1)
small = get_thumbnail(obj.img, '36x36', crop='center').url
large = get_thumbnail(obj.img, '200x200', crop='center').url
```
[sample image](https://cloud.githubusercontent.com/assets/1364479/12966312/1846b08e-d06e-11e5-9405-fd461ba67ffa.jpg)
[jpeg settings from gimp save dialog](https://cloud.githubusercontent.com/assets/1364479/12966342/5f081652-d06e-11e5-85ec-ad1c1c893fd3.png)

full error stack (note that error raised on second `get_thumbnail` statement): 
```
Traceback (most recent call last):
  File "/code/script.py", line 67, in <module>
    large = get_thumbnail(org.logo, '200x200', crop='center').url
  File "/usr/local/lib/python2.7/site-packages/sorl/thumbnail/shortcuts.py", line 8, in get_thumbnail
    return default.backend.get_thumbnail(file_, geometry_string, **options)
  File "/usr/local/lib/python2.7/site-packages/sorl/thumbnail/base.py", line 125, in get_thumbnail
    thumbnail)
  File "/usr/local/lib/python2.7/site-packages/sorl/thumbnail/base.py", line 158, in _create_thumbnail
    default.engine.write(image, options, thumbnail)
  File "/usr/local/lib/python2.7/site-packages/sorl/thumbnail/engines/base.py", line 139, in write
    progressive=progressive
  File "/usr/local/lib/python2.7/site-packages/sorl/thumbnail/engines/pil_engine.py", line 228, in _get_raw_data
    image.save(bf, **params)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 1675, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 708, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 475, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
```

**Comment by GeyseR** [comment]
this error happens on latest version of sorl-thumbnail (12.3) and on most recent versions of Pillow (2.9.0, 3.0.0, 3.1.0)

**Comment by maximkgn** [comment]
I am experiencing the exact same issue (using sorl 12.3 and Pillow 2.6.0)
First time we're seeing this problem, updated to sorl 12.3 recently.

**Comment by Darou** [comment]
Hi,

There is an issue on Pillow about this: #https://github.com/python-pillow/Pillow/issues/148

The problem with the sample image will be solved in the next release (4.2.0)

It was evaded in prior versions of sorl thanks to #29 setting ImageFile.MAXBLOCK to a high amount by default.
