### ISSUE TITLE
sorl-thumbnail stores the thumbnail in the KV store even if the original image gives a 404 error

### ISSUE THREAD

**Issue by izimobil** [mariocesar/sorl-thumbnail#442]
Hi,

I have to work with external images which I don't control and some images give 404 errors because they have been removed.

I generate thumbnails like this in my template:
`{% thumbnail obj.photo.get_absolute_url "360x270" crop="center" as im %} {{ im.url }}{% empty %}{% static "img/placeholder.png" %}{% endthumbnail %}`

When the external photo gives a 404, I would expect sorl-thumbnail to fail silently (with THUMBNAIL_DEBUG = False of course) and **not** to put an entry in the KV store (I'd like to show the placeholder in this case !) but instead it saves a path in the KV store that doesn't exists because the thumbnail was not written to disk.

In the dev server console I can see the thumbnail exceptions:

```
2016-02-11 14:17:08,412  [sorl.thumbnail.base:105]  ERROR - HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/izi/VirtualEnvs/project/local/lib/python2.7/site-packages/sorl/thumbnail/base.py", line 103, in get_thumbnail
    source_image = default.engine.get_image(source)
  File "/home/izi/VirtualEnvs/project/local/lib/python2.7/site-packages/sorl/thumbnail/engines/pil_engine.py", line 48, in get_image
    buffer = BufferIO(source.read())
  File "/home/izi/VirtualEnvs/project/local/lib/python2.7/site-packages/sorl/thumbnail/images.py", line 140, in read
    return self.storage.open(self.name).read()
  File "/home/izi/VirtualEnvs/project/local/lib/python2.7/site-packages/sorl/thumbnail/images.py", line 204, in open
    return urlopen(self.normalize_url(name))
  File "/home/izi/VirtualEnvs/project/local/lib/python2.7/site-packages/sorl/thumbnail/compat.py", line 122, in urlopen
    return _urlopen(req, timeout=settings.THUMBNAIL_URL_TIMEOUT)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
2016-02-11 14:17:08,412  [sorl.thumbnail.base:113]  WARNING - Remote file [http://example.com/foo.jpg] at [360x270] does not exist
```

My config is:
- Ubuntu 14.04
- Python 2.7
- Virtualenv
- Django==1.8.2
- redis==2.10.3
- sorl-thumbnail==12.3
- Pillow==2.9.0

My settings:
```
THUMBNAIL_KVSTORE = 'sorl.thumbnail.kvstores.redis_kvstore.KVStore'
THUMBNAIL_REDIS_DB = 3
THUMBNAIL_REDIS_HOST = 'localhost'
THUMBNAIL_REDIS_PORT = 6379
```

**Comment by izimobil** [comment]
FWIW, adding these two lines solves the problem for me:

```
diff --git a/sorl/thumbnail/base.py b/sorl/thumbnail/base.py
index 5a412e5..72cdbc8 100644
--- a/sorl/thumbnail/base.py
+++ b/sorl/thumbnail/base.py
@@ -114,7 +114,8 @@ class ThumbnailBackend(object):
                     # Will return working empty image type; 404'd image
                     logger.warn(text_type('Remote file [%s] at [%s] does not exist'),
                                 file_, geometry_string)
-
+                    if not thumbnail.exists():
+                        return None
                     return thumbnail
 
             # We might as well set the size since we have the image in memory
```

**Comment by sandeepimpressads** [comment]
Any update on this ? still having the same issue. thumbnail empty block is not called at all even though the image does not exist. Instead something is fetched from the key value store.

**Comment by Colbascov** [comment]
I think there is a bug in the UrlStorage object.
I had an HTTP Error 404: Not Found.
After some research, it turned out that in UrlStorage 
```
class UrlStorage(Storage):
    def normalize_url(self, url, charset="utf-8"):
        # Convert URL to ASCII before processing
        url = url.encode(charset, errors="ignore")
        url = url.decode("ascii", errors="ignore")
        scheme, netloc, path, qs, anchor = urlsplit(url)

        path = quote(path, b"/%")
        qs = quote_plus(qs, b":&%=")

        return urlunsplit((scheme, netloc, path, qs, anchor))

    def open(self, name, mode='rb'):
        url = self.normalize_url(name)
        python_version = platform.python_version_tuple()[0]
        user_agent = "python-urllib{python_version}/0.6".format(python_version=python_version)
        req = Request(url, headers={"User-Agent": user_agent})
        return urlopen(req, timeout=settings.THUMBNAIL_URL_TIMEOUT)
```
If the link address contains non-ascii characters, then the `normalize_url` method breaks the link.
`url.decode("ascii", errors="ignore")`  

I just added a check if image url contains non-ascii and replace them with quote function from urllib.parse module
```
from urllib.parse import quote, urlsplit, urlunsplit

url_pat = re.compile(r'^(https?|ftp):\/\/')
if type(image_source) is str and not image_source.isascii() and url_pat.match(image_source):
    scheme, netloc, path, qs, anchor = urlsplit(image_source)
    image_source = urlunsplit((scheme, netloc, quote(path), quote(qs), quote(anchor)))

image = get_thumbnail(image_source, self.geometry_string, **self.options)
```
