### ISSUE TITLE
django.db.utils.OperationalError: table "thumbnail_kvstore" already exists

### ISSUE THREAD

**Issue by MUDASSARHASHMI** [mariocesar/sorl-thumbnail#478]
Hi, I am using Django 1.8.16 and I am getting this error. I really have no clue as traceback refer to Django source code only.
I've deleted and re-added migrations but every time I get this error.
Following is full traceback:

```
(supermarekt) C:\Users\Mudassar\supermarekt\market>manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages, widget_tweaks, compressor
 django_tables2, phonenumber_field, haystack, treebeard
  Apply all migrations: sessions, admin, contenttypes, flatpages, sites, review
, catalogue, auth, thumbnail
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying thumbnail.0001_initial...Traceback (most recent call last):
  File "C:\Users\Mudassar\supermarekt\market\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
354, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 394
 in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 445
 in execute
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\django\core\management\commands\migrate.p
", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "C:\Python27\lib\site-packages\django\db\migrations\executor.py", line 1
0, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=
ake_initial)
  File "C:\Python27\lib\site-packages\django\db\migrations\executor.py", line 1
8, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Python27\lib\site-packages\django\db\migrations\migration.py", line
15, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, proje
t_state)
  File "C:\Python27\lib\site-packages\django\db\migrations\operations\models.py
, line 59, in database_forwards
    schema_editor.create_model(model)
  File "C:\Python27\lib\site-packages\django\db\backends\base\schema.py", line
86, in create_model
    self.execute(sql, params or None)
  File "C:\Python27\lib\site-packages\django\db\backends\base\schema.py", line
11, in execute
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in
execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in
execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 62, in
execute
    return self.cursor.execute(sql)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line
316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "thumbnail_kvstore" already exists
```
Please advise.

**Comment by MUDASSARHASHMI** [comment]
I've upgraded to Django 1.10 and it got resolved.
